package com.opticon.opticonnect.sdk.api.constants.commands

object DataWizardCommands {
    // Data Wizard configuration commands
    const val DATA_WIZARD_COMMAND_PREFIX_0 = "A0"
    const val DATA_WIZARD_COMMAND_PREFIX_1 = "A1"
    const val DATA_WIZARD_CONFIGURATION_0 = "[A00"
    const val DATA_WIZARD_CONFIGURATION_1 = "[A01"
    const val DATA_WIZARD_CONFIGURATION_2 = "[A02"
    const val DATA_WIZARD_CONFIGURATION_3 = "[A03"
    const val DATA_WIZARD_CONFIGURATION_4 = "[A04"
    const val DATA_WIZARD_CONFIGURATION_5 = "[A05"
    const val DATA_WIZARD_CONFIGURATION_6 = "[A06"
    const val DATA_WIZARD_CONFIGURATION_7 = "[A07"

    const val DATA_WIZARD_ENABLE_CONFIGURATION_0 = "[A0A"
    const val DATA_WIZARD_ENABLE_CONFIGURATION_1 = "[A0B"
    const val DATA_WIZARD_ENABLE_CONFIGURATION_2 = "[A0C"
    const val DATA_WIZARD_ENABLE_CONFIGURATION_3 = "[A0D"
    const val DATA_WIZARD_ENABLE_CONFIGURATION_4 = "[A0E"
    const val DATA_WIZARD_ENABLE_CONFIGURATION_5 = "[A0F"
    const val DATA_WIZARD_ENABLE_CONFIGURATION_6 = "[A0G"
    const val DATA_WIZARD_ENABLE_CONFIGURATION_7 = "[A0H"

    const val DATA_WIZARD_DISABLE_CONFIGURATION_0 = "[A0K"
    const val DATA_WIZARD_DISABLE_CONFIGURATION_1 = "[A0L"
    const val DATA_WIZARD_DISABLE_CONFIGURATION_2 = "[A0M"
    const val DATA_WIZARD_DISABLE_CONFIGURATION_3 = "[A0N"
    const val DATA_WIZARD_DISABLE_CONFIGURATION_4 = "[A0O"
    const val DATA_WIZARD_DISABLE_CONFIGURATION_5 = "[A0P"
    const val DATA_WIZARD_DISABLE_CONFIGURATION_6 = "[A0Q"
    const val DATA_WIZARD_DISABLE_CONFIGURATION_7 = "[A0R"

    const val DATA_WIZARD_ENABLE_UNPROCESSED_BEEP = "[A0+"
    const val DATA_WIZARD_DISABLE_UNPROCESSED_BEEP = "[A0-"

    const val DATA_WIZARD_RESET = "[A0\$"
    const val DATA_WIZARD_TRANSMIT_CONFIGURATION_SETTINGS = "[A0/"
    const val DATA_WIZARD_TRANSMIT_ALL_BARCODES = "[A0U"
    const val DATA_WIZARD_TRANSMIT_VALIDATED_BARCODES = "[A0V"
}
