package com.opticon.opticonnect.sdk.api.constants.commands

object DirectInputKeyCommands {
    // Numeric
    const val DIRECT_INPUT_KEY_0 = "Q0"
    const val DIRECT_INPUT_KEY_1 = "Q1"
    const val DIRECT_INPUT_KEY_2 = "Q2"
    const val DIRECT_INPUT_KEY_3 = "Q3"
    const val DIRECT_INPUT_KEY_4 = "Q4"
    const val DIRECT_INPUT_KEY_5 = "Q5"
    const val DIRECT_INPUT_KEY_6 = "Q6"
    const val DIRECT_INPUT_KEY_7 = "Q7"
    const val DIRECT_INPUT_KEY_8 = "Q8"
    const val DIRECT_INPUT_KEY_9 = "Q9"

    // Uppercase Letters
    const val DIRECT_INPUT_KEY_A = "0A"
    const val DIRECT_INPUT_KEY_B = "0B"
    const val DIRECT_INPUT_KEY_C = "0C"
    const val DIRECT_INPUT_KEY_D = "0D"
    const val DIRECT_INPUT_KEY_E = "0E"
    const val DIRECT_INPUT_KEY_F = "0F"
    const val DIRECT_INPUT_KEY_G = "0G"
    const val DIRECT_INPUT_KEY_H = "0H"
    const val DIRECT_INPUT_KEY_I = "0I"
    const val DIRECT_INPUT_KEY_J = "0J"
    const val DIRECT_INPUT_KEY_K = "0K"
    const val DIRECT_INPUT_KEY_L = "0L"
    const val DIRECT_INPUT_KEY_M = "0M"
    const val DIRECT_INPUT_KEY_N = "0N"
    const val DIRECT_INPUT_KEY_O = "0O"
    const val DIRECT_INPUT_KEY_P = "0P"
    const val DIRECT_INPUT_KEY_Q = "0Q"
    const val DIRECT_INPUT_KEY_R = "0R"
    const val DIRECT_INPUT_KEY_S = "0S"
    const val DIRECT_INPUT_KEY_T = "0T"
    const val DIRECT_INPUT_KEY_U = "0U"
    const val DIRECT_INPUT_KEY_V = "0V"
    const val DIRECT_INPUT_KEY_W = "0W"
    const val DIRECT_INPUT_KEY_X = "0X"
    const val DIRECT_INPUT_KEY_Y = "0Y"
    const val DIRECT_INPUT_KEY_Z = "0Z"

    // Lowercase Letters
    const val DIRECT_INPUT_KEY_a = "\$A"
    const val DIRECT_INPUT_KEY_b = "\$B"
    const val DIRECT_INPUT_KEY_c = "\$C"
    const val DIRECT_INPUT_KEY_d = "\$D"
    const val DIRECT_INPUT_KEY_e = "\$E"
    const val DIRECT_INPUT_KEY_f = "\$F"
    const val DIRECT_INPUT_KEY_g = "\$G"
    const val DIRECT_INPUT_KEY_h = "\$H"
    const val DIRECT_INPUT_KEY_i = "\$I"
    const val DIRECT_INPUT_KEY_j = "\$J"
    const val DIRECT_INPUT_KEY_k = "\$K"
    const val DIRECT_INPUT_KEY_l = "\$L"
    const val DIRECT_INPUT_KEY_m = "\$M"
    const val DIRECT_INPUT_KEY_n = "\$N"
    const val DIRECT_INPUT_KEY_o = "\$O"
    const val DIRECT_INPUT_KEY_p = "\$P"
    const val DIRECT_INPUT_KEY_q = "\$Q"
    const val DIRECT_INPUT_KEY_r = "\$R"
    const val DIRECT_INPUT_KEY_s = "\$S"
    const val DIRECT_INPUT_KEY_t = "\$T"
    const val DIRECT_INPUT_KEY_u = "\$U"
    const val DIRECT_INPUT_KEY_v = "\$V"
    const val DIRECT_INPUT_KEY_w = "\$W"
    const val DIRECT_INPUT_KEY_x = "\$X"
    const val DIRECT_INPUT_KEY_y = "\$Y"
    const val DIRECT_INPUT_KEY_z = "\$Z"

    // Function Keys
    const val FUNCTION_KEY_F1 = "8J"
    const val FUNCTION_KEY_F2 = "8K"
    const val FUNCTION_KEY_F3 = "8L"
    const val FUNCTION_KEY_F4 = "8M"
    const val FUNCTION_KEY_F5 = "8N"
    const val FUNCTION_KEY_F6 = "8O"
    const val FUNCTION_KEY_F7 = "8P"
    const val FUNCTION_KEY_F8 = "8Q"
    const val FUNCTION_KEY_F9 = "8R"
    const val FUNCTION_KEY_F10 = "8S"
    const val FUNCTION_KEY_F11 = "8T"
    const val FUNCTION_KEY_F12 = "8U"

    // Special Characters
    const val SPECIAL_CHAR_SPACE = "5A"
    const val SPECIAL_CHAR_EXCLAMATION = "5B"
    const val SPECIAL_CHAR_DOUBLE_QUOTE = "5C"
    const val SPECIAL_CHAR_HASH = "5D"
    const val SPECIAL_CHAR_DOLLAR = "5E"
    const val SPECIAL_CHAR_PERCENT = "5F"
    const val SPECIAL_CHAR_AMPERSAND = "5G"
    const val SPECIAL_CHAR_SINGLE_QUOTE = "5H"
    const val SPECIAL_CHAR_OPEN_PAREN = "5I"
    const val SPECIAL_CHAR_CLOSE_PAREN = "5J"
    const val SPECIAL_CHAR_ASTERISK = "5K"
    const val SPECIAL_CHAR_PLUS = "5L"
    const val SPECIAL_CHAR_COMMA = "5M"
    const val SPECIAL_CHAR_MINUS = "5N"
    const val SPECIAL_CHAR_PERIOD = "5O"
    const val SPECIAL_CHAR_SLASH = "5P"
    const val SPECIAL_CHAR_COLON = "6A"
    const val SPECIAL_CHAR_SEMICOLON = "6B"
    const val SPECIAL_CHAR_LESS_THAN = "6C"
    const val SPECIAL_CHAR_EQUAL = "6D"
    const val SPECIAL_CHAR_GREATER_THAN = "6E"
    const val SPECIAL_CHAR_QUESTION_MARK = "6F"
    const val SPECIAL_CHAR_AT_SYMBOL = "6G"
    const val SPECIAL_CHAR_OPEN_BRACKET = "7A"
    const val SPECIAL_CHAR_BACKSLASH = "7B"
    const val SPECIAL_CHAR_CLOSE_BRACKET = "7C"
    const val SPECIAL_CHAR_CARET = "7D"
    const val SPECIAL_CHAR_UNDERSCORE = "7E"
    const val SPECIAL_CHAR_BACKTICK = "7F"
    const val SPECIAL_CHAR_OPEN_BRACE = "9T"
    const val SPECIAL_CHAR_PIPE = "9U"
    const val SPECIAL_CHAR_CLOSE_BRACE = "9V"
    const val SPECIAL_CHAR_TILDE = "9W"

    // Control Characters
    const val CONTROL_NULL = "9G"
    const val CONTROL_SOH = "1A"
    const val CONTROL_STX = "1B"
    const val CONTROL_ETX = "1C"
    const val CONTROL_EOT = "1D"
    const val CONTROL_ENQ = "1E"
    const val CONTROL_ACK = "1F"
    const val CONTROL_BEL = "1G"
    const val CONTROL_BS = "1H"
    const val CONTROL_HT = "1I"
    const val CONTROL_LF = "1J"
    const val CONTROL_VT = "1K"
    const val CONTROL_FF = "1L"
    const val CONTROL_CR = "1M"
    const val CONTROL_SO = "1N"
    const val CONTROL_SI = "1O"
    const val CONTROL_DLE = "1P"
    const val CONTROL_DC1 = "1Q"
    const val CONTROL_DC2 = "1R"
    const val CONTROL_DC3 = "1S"
    const val CONTROL_DC4 = "1T"
    const val CONTROL_NAK = "1U"
    const val CONTROL_SYN = "1V"
    const val CONTROL_ETB = "1W"
    const val CONTROL_CAN = "1X"
    const val CONTROL_EM = "1Y"
    const val CONTROL_SUB = "1Z"
    const val CONTROL_ESCAPE = "9A"
    const val CONTROL_FS = "9B"
    const val CONTROL_GS = "9C"
    const val CONTROL_RS = "9D"
    const val CONTROL_US = "9E"
    const val CONTROL_DEL_ASCII = "9F"

    // Code Identification/Length
    const val CODE_IDENTIFICATION = "\$2"
    const val CODE_IDENTIFICATION_ISO = "\$1"
    const val CODE_IDENTIFICATION_BT = "\$BT"
    const val CODE_LENGTH_2_DIGITS = "\$3"
    const val CODE_LENGTH_6_DIGITS = "\$6"

    // Special
    const val SPECIAL_READ_DIRECTION = "\$4"
    const val SPECIAL_TIMESTAMP = "\$TM"
}
